// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoHsj_Beta.Models;

#nullable disable

namespace ProyectoHsj_Beta.Migrations
{
    [DbContext(typeof(HoySeJuegaContext))]
    partial class HoySeJuegaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("ID_permiso");

                    b.HasKey("IdRol", "IdPermiso")
                        .HasName("PK__PERMISO___9F614A336556D35C");

                    b.HasIndex("IdPermiso");

                    b.ToTable("PERMISO_ROL", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.AccionRealizadum", b =>
                {
                    b.Property<int>("IdAccionRealizada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_accion_realizada");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccionRealizada"));

                    b.Property<string>("TituloAccionRealizada")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Titulo_Accion_Realizada");

                    b.HasKey("IdAccionRealizada")
                        .HasName("PK__ACCION_R__2DC6E876AE3CA4B6");

                    b.ToTable("ACCION_REALIZADA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Auditorium", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_auditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("DescripcionDeAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion_De_Accion");

                    b.Property<DateTime>("FechaAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Auditoria")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdAccionRealizada")
                        .HasColumnType("int")
                        .HasColumnName("ID_accion_realizada");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.HasKey("IdAuditoria")
                        .HasName("PK__AUDITORI__F6FFFB8CE3101847");

                    b.HasIndex("IdAccionRealizada");

                    b.HasIndex("IdUsuario");

                    b.ToTable("AUDITORIA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Cancha", b =>
                {
                    b.Property<int>("IdCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_cancha");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCancha"));

                    b.Property<string>("NombreCancha")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Nombre_Cancha");

                    b.Property<string>("UbicacionCancha")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Ubicacion_Cancha");

                    b.HasKey("IdCancha")
                        .HasName("PK__CANCHA__A2D3DBCF8F513BBF");

                    b.ToTable("CANCHA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.EstadoReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_estado_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("NombreEstadoReserva")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Nombre_Estado_Reserva");

                    b.HasKey("IdEstadoReserva")
                        .HasName("PK__ESTADO_R__746A84F0EE561664");

                    b.ToTable("ESTADO_RESERVA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.HistorialReserva", b =>
                {
                    b.Property<int>("IdHistorialReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialReserva"));

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("ID_usuario")
                        .HasColumnType("int");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonoUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdHistorialReserva");

                    b.ToTable("HistorialReservas", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.HorarioDisponible", b =>
                {
                    b.Property<int>("IdHorarioDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_horario_disponible");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorarioDisponible"));

                    b.Property<bool?>("DisponibleHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Disponible_Horario");

                    b.Property<DateOnly>("FechaHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Horario")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Inicio");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int")
                        .HasColumnName("ID_cancha");

                    b.HasKey("IdHorarioDisponible")
                        .HasName("PK__HORARIO___7D5601B788E66056");

                    b.HasIndex("IdCancha");

                    b.ToTable("HORARIO_DISPONIBLE", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaEnvioNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Envio_Notificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    b.Property<int>("IdTituloNotificacion")
                        .HasColumnType("int")
                        .HasColumnName("ID_titulo_notificacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.Property<string>("MensajeNotificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mensaje_Notificacion");

                    b.HasKey("IdNotificacion")
                        .HasName("PK__NOTIFICA__99BC7E5EC04B01F2");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdTituloNotificacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("NOTIFICACION", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Pago")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Monto_Pago");

                    b.HasKey("IdPago")
                        .HasName("PK__PAGO__808903EC47A081C7");

                    b.HasIndex("IdReserva");

                    b.ToTable("PAGO", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_permiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre_Permiso");

                    b.HasKey("IdPermiso")
                        .HasName("PK__PERMISO__74B1E219FA556AF3");

                    b.ToTable("PERMISO", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<short>("AnioReporte")
                        .HasColumnType("smallint")
                        .HasColumnName("Anio_Reporte");

                    b.Property<string>("DescripcionReporte")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Descripcion_Reporte");

                    b.Property<DateTime?>("FechaDeReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_De_Reporte")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdTituloReporte")
                        .HasColumnType("int")
                        .HasColumnName("ID_titulo_reporte");

                    b.Property<byte>("MesReporte")
                        .HasColumnType("tinyint")
                        .HasColumnName("Mes_Reporte");

                    b.Property<int?>("ReservasRealizadasReporte")
                        .HasColumnType("int")
                        .HasColumnName("Reservas_Realizadas_Reporte");

                    b.Property<int?>("UsuariosRegistradosReporte")
                        .HasColumnType("int")
                        .HasColumnName("Usuarios_Registrados_Reporte");

                    b.HasKey("IdReporte")
                        .HasName("PK__REPORTE__41AEEB64E2FCCC33");

                    b.HasIndex("IdTituloReporte");

                    b.ToTable("REPORTE", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime?>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Reserva")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("int")
                        .HasColumnName("ID_estado_reserva");

                    b.Property<int>("IdHorarioDisponible")
                        .HasColumnType("int")
                        .HasColumnName("ID_horario_disponible");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    b.HasKey("IdReserva")
                        .HasName("PK__RESERVA__CD692CB066E0B8CB");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("IdHorarioDisponible");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RESERVA", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre_Rol");

                    b.HasKey("IdRol")
                        .HasName("PK__ROL__182A5412E3FEA872");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.TituloNotificacion", b =>
                {
                    b.Property<int>("IdTituloNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_titulo_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTituloNotificacion"));

                    b.Property<string>("TituloNotificacion1")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Titulo_Notificacion");

                    b.HasKey("IdTituloNotificacion")
                        .HasName("PK__TITULO_N__DA36445EB454B7E0");

                    b.ToTable("TITULO_NOTIFICACION", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.TituloReporte", b =>
                {
                    b.Property<int>("IdTituloReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_titulo_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTituloReporte"));

                    b.Property<string>("TituloReporte1")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Titulo_Reporte");

                    b.HasKey("IdTituloReporte")
                        .HasName("PK__TITULO_R__5F9C0CCDB6AEF5F9");

                    b.ToTable("TITULO_REPORTE", (string)null);
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Apellido_Usuario");

                    b.Property<string>("ContraseniaUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Contrasenia_Usuario");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Correo_Usuario");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Nombre_Usuario");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<int>("TelefonoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Telefono_Usuario");

                    b.HasKey("IdUsuario")
                        .HasName("PK__USUARIO__DF3D425202CA1D01");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "CorreoUsuario" }, "UQ__USUARIO__A7126311EFE6490D")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("FK__PERMISO_R__ID_pe__45F365D3");

                    b.HasOne("ProyectoHsj_Beta.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__PERMISO_R__ID_ro__46E78A0C");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Auditorium", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.AccionRealizadum", "IdAccionRealizadaNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdAccionRealizada")
                        .IsRequired()
                        .HasConstraintName("FK__AUDITORIA__ID_ac__4CA06362");

                    b.HasOne("ProyectoHsj_Beta.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__AUDITORIA__ID_us__4D94879B");

                    b.Navigation("IdAccionRealizadaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.HorarioDisponible", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.Cancha", "IdCanchaNavigation")
                        .WithMany("HorarioDisponibles")
                        .HasForeignKey("IdCancha")
                        .IsRequired()
                        .HasConstraintName("FK__HORARIO_D__ID_ca__5441852A");

                    b.Navigation("IdCanchaNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Notificacion", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__NOTIFICAC__ID_re__6754599E");

                    b.HasOne("ProyectoHsj_Beta.Models.TituloNotificacion", "IdTituloNotificacionNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdTituloNotificacion")
                        .IsRequired()
                        .HasConstraintName("FK__NOTIFICAC__ID_ti__656C112C");

                    b.HasOne("ProyectoHsj_Beta.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__NOTIFICAC__ID_us__66603565");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdTituloNotificacionNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Pago", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdReserva")
                        .IsRequired()
                        .HasConstraintName("FK__PAGO__ID_reserva__5FB337D6");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Reporte", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.TituloReporte", "IdTituloReporteNavigation")
                        .WithMany("Reportes")
                        .HasForeignKey("IdTituloReporte")
                        .IsRequired()
                        .HasConstraintName("FK__REPORTE__ID_titu__3A81B327");

                    b.Navigation("IdTituloReporteNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Reserva", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.EstadoReserva", "IdEstadoReservaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .IsRequired()
                        .HasConstraintName("FK__RESERVA__ID_esta__59FA5E80");

                    b.HasOne("ProyectoHsj_Beta.Models.HorarioDisponible", "IdHorarioDisponibleNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdHorarioDisponible")
                        .IsRequired()
                        .HasConstraintName("FK__RESERVA__ID_hora__5BE2A6F2");

                    b.HasOne("ProyectoHsj_Beta.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__RESERVA__ID_usua__5AEE82B9");

                    b.Navigation("IdEstadoReservaNavigation");

                    b.Navigation("IdHorarioDisponibleNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoHsj_Beta.Models.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__USUARIO__ID_rol__412EB0B6");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.AccionRealizadum", b =>
                {
                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Cancha", b =>
                {
                    b.Navigation("HorarioDisponibles");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.HorarioDisponible", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Reserva", b =>
                {
                    b.Navigation("Notificacions");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.TituloNotificacion", b =>
                {
                    b.Navigation("Notificacions");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.TituloReporte", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("ProyectoHsj_Beta.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Notificacions");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
